name: Compile OpenJDK with jdk-macos-legacy patches

on:
    push:
    pull_request:
    workflow_dispatch:
    release:
      types: [published]

jobs:
    build:
        name: Build OpenJDK versions
        runs-on: macos-14

        steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Install dependencies
          run: |
                brew install autoconf

        - name: Clone OpenJDK
          run: |
                git clone https://github.com/openjdk/jdk17u.git --depth 1 --branch jdk-17.0.12+0

        - name: Apply patches
          run: |
                cd jdk17u
                git apply ../patches/17/10.8.patch
                git apply ../patches/17/awtwindow.patch
                git apply ../patches/17/remove_disconnectx.patch
                git apply ../patches/17/remove_metal_backend.patch

        - name: Run patch scripts
          run: |
                bash patches/17/remove_metal_backend.sh jdk17u

        - name: Configure
          run: |
                cd jdk17u
                arch -x86_64 bash configure --disable-precompiled-headers --with-debug-level=release --with-native-debug-symbols=none --with-extra-cxxflags="-stdlib=libc++" --enable-warnings-as-errors=no --with-conf-name=release --with-vendor-name="Jazzzny" --without-version-opt --without-version-pre --with-vendor-version-string="jdk-macos-legacy"
                make images

        - name: Archive the build folder
          run: |
                cd jdk17u
                tar -czf jdk-macos-legacy.tar.gz build

        - name: Upload the build folder
          uses: actions/upload-artifact@v4
          with:
            name: jdk-macos-legacy
            path: jdk17u/jdk-macos-legacy.tar.gz




