name: Compile OpenJDK with jdk-macos-legacy patches

on:
    workflow_dispatch:

jobs:
    build:
        name: Build OpenJDK versions
        runs-on: macos-14

        steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Install dependencies
          run: |
                brew install autoconf

        - name: Clone OpenJDK
          run: |
                git clone https://github.com/openjdk/jdk17u.git --depth 1 --branch jdk-17.0.12+2

        - name: Apply patches
          run: |
                cd jdk17u
                git apply ../patches/17/10.8.patch
                git apply ../patches/17/awtwindow.patch
                git apply ../patches/17/remove_disconnectx.patch
                git apply ../patches/17/remove_metal_backend.patch

        - name: Run patch scripts
          run: |
                bash patches/17/remove_metal_backend.sh jdk17u

        - name: Configure
          run: |
                cd jdk17u
                arch -x86_64 bash configure --disable-precompiled-headers --with-debug-level=release --with-native-debug-symbols=none --with-extra-cxxflags="-stdlib=libc++" --enable-warnings-as-errors=no --with-conf-name=release --with-vendor-name="Jazzzny" --without-version-opt --without-version-pre --with-vendor-version-string="jdk-macos-legacy"
                make images

        - name: Clone Adoptium packaging scripts
          run: |
                git clone https://github.com/adoptium/installer.git

        - name: Run packaging scripts
          run: |
                cd installer
                ./pkgbuild/packagesbuild.sh --major_version 17 --full_version 17.0.12+2 --input_directory ../jdk17u/build/release/images/jdk-bundle/jdk-17.0.12.jdk --output_directory ../jdk17u/build/release/images/jdk-bundle/jdk-17.0.12+2.pkg --jvm hotspot --architecture x86_64 --type jdk --vendor jazzzny --package-name OpenJDK --logo /System/Library/CoreServices/JavaLauncher.app/Contents/Resources/class.icns

        - name: Archive the jdk image
          run: |
                cd jdk17u/build/release/images/jdk-bundle
                tar -czf jdk-macos-legacy.tar.gz jdk-17.0.12.jdk

        - name: Upload JDK installer
          uses: actions/upload-artifact@v4
          with:
            name: jdk
            path: jdk17u/build/release/images/jdk-bundle/jdk-17.0.12+2.pkg

        - name: Upload JDK image
          uses: actions/upload-artifact@v4
          with:
            name: jdk-image
            path: jdk17u/build/release/images/jdk-bundle/jdk-macos-legacy.tar.gz




